development:
  sessions:
    default:
      uri: mongodb://remote-timer:alocsmey@kahana.mongohq.com:10082/remote-timers

production:
  sessions:
    default:
      uri: mongodb://remote-timer:alocsmey@kahana.mongohq.com:10082/remote-timers
